export const GET_GLOBAL_DATA = 'GET_GLOBAL_DATA'
export const GLOBAL_DATA_LOADING = 'GLOBAL_DATA_LOADING'
export const DAILY_DATA_LOADING = 'DAILY_DATA_LOADING'
export const UPDATE_DATA = 'UPDATE_DATA'
export const DAILY_DATA_RECEIVED = 'DAILY_DATA_RECEIVED'

